### ISSUE TITLE
Fail to attempt to call method 'on_connected' (a nil value)

### ISSUE THREAD

**Issue by mauricioribeiro** [pusher-community/pusher-nodemcu-client#1]
Hi! I'm getting the following error when I try to bind on_connection event:

**PANIC: unprotected error in call to Lua API (pusher_client.lua:124: attempt to call method 'on_connected' (a nil value))**

I tried to figure out how to solve it reading the pusher_client.lua lines but without success... :/

My code:
```
dofile("pusher_client.lua")
local pusher_client = pusher.createClient('myappkeyhere')

pusher_client.on_close = function() print("client disconnected") end
pusher_client.on_connection = function(client, socket_id)
  print("connected")
  client:subscribe('house-2').bind('turn-light', function() print("event received") end)
end

pusher_client:connect()
```

Any help?

**Comment by mdpye** [comment]
I'm no expert, but I find this line suspicious. It calls `self.on_connected` protected by a `nil` check for `on_connection` :/

https://github.com/pusher-community/pusher-nodemcu-client/blob/master/pusher_client.lua#L126

Paging @luismfonseca

**Comment by mauricioribeiro** [comment]
Exactly. I renamed it to on_connection but didn't work 😕

**Comment by luismfonseca** [comment]
I don't have a nodemcu with me atm so I can't test it.

I'd suggest replacing _all_ occurrences for `on_connected` to `on_connection`. Besides line 126, that also includes lines 99 and 101.

**Comment by luismfonseca** [comment]
I was able to replicate the issue and tested the proposed changes. It seems to work with me, so I'm closing the issue.

Feel free to try out the new version and continue this discussion if the issue persists.
